server:
  port: 8081
spring:
  profiles:
    active: local
db:
  database: hm-item
hm:
  swagger:
    title: 商品服务接口文档
    package: com.hmall.item.controller
  jwt:
    location: classpath:hmall.jks
    alias: hmall
    password: hmall123
    tokenTTL: 30m
  auth:
    excludePaths:
      - /search/**
      - /users/login
      - /items/**
      - /hi
      -
# keytool -genkeypair -alias hmall -keyalg RSA -keypass hmall123 -keystore hmall.jks -storepass hmall123
