server:
  port: 8085
spring:
  application:
    name: trade-service
  profiles:
    active: local
db:
  database: hm-trade
hm:
  swagger:
    title: 交易服务接口
    package: com.hmall.trade.controller
  jwt:
    location: classpath:hmall.jks
    alias: hmall
    password: hmall123
    tokenTTL: 30m
  auth:
    excludePaths:
      - /search/**
      - /users/login
      - /items/**
      - /hi
      -
# keytool -genkeypair -alias hmall -keyalg RSA -keypass hmall123 -keystore hmall.jks -storepass hmall123
